name: Setup Alpine Linux
description: Setup Alpine Linux (WIP)
author: Jakub Jirutka <jakub@jirutka.cz>
branding:
  color: blue
  icon: terminal
inputs:
  apk-tools-url:
    description: >
      URL of the apk-tools static binary to use. It must end with `#!sha256!` followed by a SHA-256
      hash of the file.
      This should normally be left at the default value.
    required: false
    default: https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic/v2.12.9/x86_64/apk.static#!sha256!5176da3d4c41f12a08b82809aca8e7e2e383b7930979651b8958eca219815af5
  arch:
    description: >
      CPU architecture to emulate using QEMU. Allowed values are: `x86_64` (native), `x86` (native),
      `aarch64`, `armhf` (armv6 with hard-float), `armv7`, `ppc64le`, `riscv64` (available only
      for branch `edge`), and `s390x`
    required: false
    default: x86_64
  branch:
    description: Alpine branch (aka release) to install (e.g. `v3.15`, `latest-stable`, `edge`).
    required: false
    default: latest-stable
  extra-repositories:
    description: >
      A list of additional Alpine repositories to add into /etc/apk/repositories (Alpine's official
      main and community repositories are always added).
    required: false
    default: ''
  mirror-url:
    description: URL of an Alpine Linux mirror to fetch packages from.
    required: false
    default: http://dl-cdn.alpinelinux.org/alpine
  packages:
    description: A list of Alpine packages to install.
    required: false
    default: ''
  shell-name:
    description: >
      Name of the script to run `sh` in the Alpine chroot that will be added to `GITHUB_PATH`.
      This name should be used in `jobs.<job_id>.steps[*].shell` (e.g. `shell: alpine.sh {0}`) to
      run the step's script in the chroot.
    required: false
    default: alpine.sh
  volumes:
    description: >
      A list of directories on the host system to mount bind into the chroot. You can specify the
      source and destination path: `<src-dir>:<dest-dir>``. The `<src-dir>` is an absolute path of
      existing directory on the host system, `<dest-dir>` is an absolute path in the chroot
      (it will be created if doesn't exist). You can omit the latter if they're the same.

      Please note that /home/runner/work (where's your workspace located) is always mounted,
      don't specify it here.
    required: false
    default: ''
outputs:
  root-path:
    description: >
      Path to the created Alpine root directory (also exposed in environment
      variable ALPINE_ROOT_PATH).
    value: ${{ steps.setup.outputs.root-path }}

runs:
  using: composite
  steps:
    - id: setup
      env:
        INPUT_APK_TOOLS_URL: ${{ inputs.apk-tools-url }}
        INPUT_ARCH: ${{ inputs.arch }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_EXTRA_REPOSITORIES: ${{ inputs.extra-repositories }}
        INPUT_MIRROR_URL: ${{ inputs.mirror-url }}
        INPUT_PACKAGES: ${{ inputs.packages }}
        INPUT_SHELL_NAME: ${{ inputs.shell-name }}
        INPUT_VOLUMES: ${{ inputs.volumes }}
      run: sudo -E ./setup-alpine.sh
      working-directory: ${{ github.action_path }}
      shell: bash

    - uses: webiny/action-post-run@2.0.1
      with:
        run: sudo "${{ steps.setup.outputs.root-path }}"/destroy.sh
