= Setup Alpine GitHub Action
:proj-name: setup-alpine
:gh-name: jirutka/{proj-name}
:gh-branch: master
:action-ref: {gh-name}@{gh-branch}
:alpine-latest: v3.15


== Parameters

=== Inputs

apk-tools-url::
URL of the apk-tools static binary to use.
It must end with `#!sha256!` followed by a SHA-256 hash of the file.
This should normally be left at the default value.
+
Default: _see link:action.yml[]_

arch::
CPU architecture to emulate using https://www.qemu.org/docs/master/user/main.html[QEMU user space emulator].
Allowed values are: `x86_64` (native), `x86` (native), `aarch64`, `armhf` footnote:[armhf is armv6 with hard-float.], `armv7`, `ppc64le`, `riscv64` footnote:[riscv64 is available only for branch `edge` for now.], and `s390x`.
+
Default: `x86_64`

branch::
Alpine branch (aka release) to install: `vMAJOR.MINOR`, `latest-stable`, or `edge`.
+
Example: `{alpine-latest}` +
Default: `latest-stable`

extra-repositories::
A list of additional Alpine repositories to add into _/etc/apk/repositories_ (Alpine’s official _main_ and _community_ repositories are always added).
+
Example: `http://dl-cdn.alpinelinux.org/alpine/edge/testing`

mirror-url::
URL of an Alpine Linux mirror to fetch packages from.
+
Default: `http://dl-cdn.alpinelinux.org/alpine`

packages::
A list of Alpine packages to install.
+
Example: `build-base openssh-client` +
Default: _no extra packages_

shell-name::
Name of the script to run `sh` in the Alpine chroot that will be added to `GITHUB_PATH`.
This name should be used in `jobs.<job_id>.steps[*].shell` (e.g. `shell: alpine-sh {0}`) to run the step’s script in the chroot.
+
Default: `alpine.sh`

volumes::
A list of directories on the host system to mount bind into the chroot.
You can specify the source and destination path: `<src-dir>:<dest-dir>`.
The `<src-dir>` is an absolute path of existing directory on the host system, `<dest-dir>` is an absolute path in the chroot (it will be created if doesn’t exist).
You can omit the latter if they're the same.
+
Please note that _/home/runner/work_ (where’s your workspace located) is always mounted, don’t specify it here.
+
Example: `${{ steps.alpine-aarch64.outputs.root-path }}:/mnt/alpine-aarch64`


=== Outputs

root-path::
Path to the created Alpine root directory.


== Usage examples

=== Basic usage

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2

  - name: Setup latest Alpine Linux
    uses: {action-ref}

  - name: Run script inside Alpine chroot as root
    run: |
      cat /etc/alpine-release
      apk add nodejs npm
    shell: alpine.sh --root {0}

  - name: Run script inside Alpine chroot as the default user (unprivileged)
    run: |
      ls -la  # as you would expect, you're in your workspace directory
      npm build
    shell: alpine.sh {0}

  - name: Run script on the host system (Ubuntu)
    run: |
      cat /etc/os-release
    shell: bash
----


=== Set up Alpine with specified packages

[source, yaml, subs="+attributes"]
----
- uses: {action-ref}
  with:
    branch: {alpine-latest}
    packages: >
      build-base
      libgit2-dev
      meson
----


=== Set up and use Alpine for a different CPU architecture

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
steps:
  - name: Setup Alpine Linux {alpine-latest} for aarch64
    uses: {action-ref}
    with:
      arch: aarch64
      branch: {alpine-latest}

  - name: Run script inside Alpine chroot with aarch64 emulation
    run: uname -m
    shell: alpine.sh {0}
----


=== Set up Alpine with packages from the testing repository

[source, yaml, subs="+attributes"]
----
- uses: {action-ref}
  with:
    extra-repositories: |
      http://dl-cdn.alpinelinux.org/alpine/edge/testing
    packages: some-pkg-from-testing
----


=== Set up and use multiple Alpine environments in a single job

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
steps:
  - name: Setup latest Alpine Linux for x86_64
    uses: {action-ref}
    with:
      shell-name: alpine-aarch64.sh

  - name: Setup latest Alpine Linux for aarch64
    uses: {action-ref}
    with:
      arch: aarch64
      shell-name: alpine-aarch64.sh

  - name: Run script inside Alpine chroot
    run: uname -m
    shell: alpine-x86_64.sh {0}

  - name: Run script inside Alpine chroot with aarch64 emulation
    run: uname -m
    shell: alpine-aarch64.sh {0}

  - name: Run script on the host system (Ubuntu)
    run: cat /etc/os-release
    shell: bash
----


=== Cross-compile Rust application with system libraries

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
strategy:
  matrix:
    include:
      - rust-target: aarch64-unknown-linux-musl
        os-arch: aarch64
env:
  CROSS_SYSROOT: /mnt/alpine-${{ matrix.os-arch }}
steps:
  - uses: actions/checkout@v1

  - name: Set up Alpine Linux for ${{ matrix.os-arch }} (target arch)
    id: alpine-target
    uses: {action-ref}
    with:
      arch: ${{ matrix.os-arch }}
      branch: edge
      packages: >
        dbus-dev
        dbus-static
      shell-name: alpine-target.sh

  - name: Set up Alpine Linux for x86_64 (build arch)
    uses: {action-ref}
    with:
      arch: x86_64
      packages: >
        build-base
        pkgconf
        lld
        rustup
      volumes: ${{ steps.alpine-target.outputs.root-path }}:${{ env.CROSS_SYSROOT }}
      shell-name: alpine.sh

  - name: Install Rust stable toolchain via rustup
    run: rustup-init --target ${{ matrix.rust-target }} --default-toolchain stable --profile minimal -y
    shell: alpine.sh {0}

  - name: Build statically linked binary
    env:
      CARGO_BUILD_TARGET: ${{ matrix.rust-target }}
      CARGO_PROFILE_RELEASE_STRIP: symbols
      PKG_CONFIG_ALL_STATIC: '1'
      PKG_CONFIG_LIBDIR: ${{ env.CROSS_SYSROOT }}/usr/lib/pkgconfig
      RUSTFLAGS: -C linker=/usr/bin/ld.lld
      SYSROOT: /dummy  # workaround for https://github.com/rust-lang/pkg-config-rs/issues/102
    run: |
      # Workaround for https://github.com/rust-lang/pkg-config-rs/issues/102.
      echo -e '#!/bin/sh\nPKG_CONFIG_SYSROOT_DIR=${{ env.CROSS_SYSROOT }} exec pkgconf "$@"' \
          | install -m755 /dev/stdin pkg-config
      export PKG_CONFIG="$(pwd)/pkg-config"
      cargo build --release --locked --verbose
    shell: alpine.sh {0}

  - name: Try to run the binary
    run: ./myapp --version
    working-directory: target/${{ matrix.rust-target }}/release
    shell: alpine-target.sh {0}
----


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
