= Setup Alpine GitHub Action
:proj-name: setup-alpine
:gh-name: jirutka/{proj-name}
:gh-branch: master
:action-ref: {gh-name}@{gh-branch}


== Examples

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
steps:
  - name: Checkout your repository
    uses: actions/checkout@v2

  - name: Setup latest Alpine Linux
    uses: {action-ref}

  - name: Run script inside Alpine chroot as the default user (unprivileged)
    run: |
      cat /etc/alpine-release
      ls -la  # as you would expect, you're in your project's directory
    shell: alpine.sh {0}

  - name: Run script inside Alpine chroot as root
    run: apk add nodejs
    shell: alpine.sh --root {0}

  - name: Run script on the host system (Ubuntu)
    run: cat /etc/os-release
----

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
steps:
  - name: Setup Alpine Linux v3.15 for aarch64
    uses: {action-ref}
    with:
      arch: aarch64
      branch: v3.15

  - name: Run script inside Alpine chroot with aarch64 emulation
    run: uname -m
    shell: alpine.sh {0}
----

[source, yaml, subs="+attributes"]
----
- name: Setup latest Alpine Linux with build-base and cargo packages
  uses: {action-ref}
  with:
    packages: build-base cargo
----

[source, yaml, subs="+attributes"]
----
- name: Setup latest Alpine Linux with packages from the testing repository
  uses: {action-ref}
  with:
    packages: some-pkg-from-testing
    extra-repositories: |
      http://dl-cdn.alpinelinux.org/alpine/edge/testing
----

[source, yaml, subs="+attributes"]
----
runs-on: ubuntu-latest
steps:
  - name: Setup latest Alpine Linux for x86_64
    uses: {gh-name}@{version}
    with:
      shell-name: alpine-aarch64.sh

  - name: Setup latest Alpine Linux for aarch64
    uses: {gh-name}@{version}
    with:
      arch: aarch64
      shell-name: alpine-aarch64.sh

  - name: Run script inside Alpine chroot
    run: uname -m
    shell: alpine-x86_64.sh {0}

  - name: Run script inside Alpine chroot with aarch64 emulation
    run: uname -m
    shell: alpine-aarch64.sh {0}

  - name: Run script on the host system (Ubuntu)
    run: cat /etc/os-release
----


== Inputs

apk-tools-url::
URL of the apk-tools static binary to use.
It must end with `#!sha256!` followed by a SHA-256 hash of the file.
This should normally be left at the default value.
+
Default: _see link:action.yml[]_

arch::
CPU architecture to emulate using QEMU.
Allowed values are: `x86_64` (native), `x86` (native), `aarch64`, `armhf` footnote:[armhf is armv6 with hard-float.], `armv7`, `ppc64le`, `riscv64` footnote:[riscv64 is available only for branch `edge` for now.], and `s390x`.
+
Default: `x86_64`

branch::
Alpine branch (aka release) to install: `vMAJOR.MINOR`, `latest-stable`, or `edge`.
+
Example: `v3.15` +
Default: `latest-stable`

extra-repositories::
A list of additional Alpine repositories to add into _/etc/apk/repositories_ (Alpine’s official _main_ and _community_ repositories are always added).
+
Example: `http://dl-cdn.alpinelinux.org/alpine/edge/testing`

mirror-url::
URL of an Alpine Linux mirror to fetch packages from.
+
Default: `http://dl-cdn.alpinelinux.org/alpine`

packages::
A list of Alpine packages to install.
+
Example: `build-base openssh-client` +
Default: _no extra packages_

shell-name::
Name of the script to run `sh` in the Alpine chroot that will be added to `GITHUB_PATH`.
This name should be used in `jobs.<job_id>.steps[*].shell` (e.g. `shell: alpine-sh {0}`) to run the step’s script in the chroot.
+
Default: `alpine.sh`

volumes::
A list of directories on the host system to mount bind into the chroot.
You can specify the source and destination path: `<src-dir>:<dest-dir>`.
The `<src-dir>` is an absolute path of existing directory on the host system, `<dest-dir>` is an absolute path in the chroot (it will be created if doesn’t exist).
You can omit the latter if they're the same.
+
Please note that _/home/runner/work_ (where’s your workspace located) is always mounted, don’t specify it here.
+
Example: `${{ steps.alpine-aarch64.outputs.root-path }}:/mnt/alpine-aarch64`


== Outputs

root-path::
Path to the created Alpine root directory.


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
